services:
  fritzbox_exporter:
    image: fritzbox_exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure:2
    container_name: fritzbox_exporter
    ports:
      - 9042:9042
    volumes:
      - ./metrics-upnp.json:/metrics-upnp.json
      - ./metrics-lua.json:/metrics-lua.json
    env_file:
      - .env