version: '3.4'

services:
  fritzbox_exporter:
    image: fritzbox_exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: fritzbox_exporter
    network_mode: "host" 
    ports:
      - 9042:9042
    env_file:
      - .env
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m
